apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eventstore.fullname" . }}-admin
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "eventstore.name" . }}
    helm.sh/chart: {{ include "eventstore.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: admin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eventstore.name" . }}-admin
      app.kubernetes.io/instance: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "eventstore.name" . }}-admin
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: admin
      {{- if .Values.adminPodAnnotations }}
      annotations:
{{ toYaml .Values.adminPodAnnotations | indent 8 }}
      {{- end }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
      containers:
        - name: proxy
          image: "{{ .Values.admin.proxyImage }}:{{ .Values.admin.proxyImageTag }}"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
          volumeMounts:
            - name: config
              mountPath: "/etc/nginx/conf.d"
              readOnly: true
          ports:
            - containerPort: {{ .Values.extHttpPort }}
          livenessProbe:
            httpGet:
              path: /_liveness
              port: {{ .Values.extHttpPort }}
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 15
      volumes:
        - name: config
          configMap:
            name: {{ include "eventstore.fullname" . }}-admin
